Add -llog, and do not use -fstack-protector.
This fixes this compile error:

    error: undefined reference to '__stack_chk_fail_local'

Solution as per
http://trac.pjsip.org/repos/wiki/Getting-Started/Android#BuildingPJSIP .

-llog is added to avoid android-specific code within recipes.
It should be everywhere if a library supports sane logging.